django_project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.front, name="blog-front"),
    path('home/', views.home, name = 'blog-home'),
    path('classification/', views.classification, name = 'blog-classification'),
    path('fun-facts/', views.funfacts, name = 'blog-funfacts'),
    path('Sorted/<str:animal_type>/', views.sort_animals, name='blog-animals'),
    path('Sorted-link/<str:animal_type>/', views.sort_animals_type, name='blog-animals2'),
    path('Animal/<str:animal_name>/', views.clicked_info, name='blog-info'),
    path('Search/', views.search, name='blog-search'),
    path('classification_info/<str:categories_type>/',views.class_view, name='class_view'),
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace = 'blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

django_project/blog/models.py
from django.db import models
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models

class Post(models.Model):
	an_type = models.CharField(max_length=100)
	animal_cat = models.CharField(max_length=50)
	animal = models.CharField(max_length=100)
	definition = models.TextField()
	location_discovered = models.CharField(max_length=100)
	location = models.CharField(max_length=100)
	more_info = models.TextField(null=True, blank=True)
	image_name = models.CharField(max_length=50)
	image = models.ImageField(upload_to="img/%y", height_field=None, width_field=None, max_length=None)
	sci_name = models.CharField(max_length=255)
	fav_food = models.CharField(max_length=255)



	def __str__(self):
		return self.animal
	
	def __str__(self):
		return self.image_name
	
class FunFact(models.Model):
	animal = models.CharField(max_length=255)
	fact = models.TextField()
	image = models.ImageField(upload_to="img/%y", height_field=None, width_field=None, max_length=None)

	def __str__(self):
		return self.animal


class Category(models.Model):
    categories_type = models.CharField(max_length=255)
    categories_description = models.TextField()
    category_image = models.ImageField(upload_to='category_images/%y')

    def __str__(self):
        return self.categories_type
	

class Category_informations(models.Model):
    categories_type = models.CharField(max_length=255)
    categories_description = models.TextField()
    category_image = models.ImageField(upload_to='category_images/%Y')
    image_one = models.ImageField(upload_to='category_images/catview_images/%Y', blank=True, null=True)
    image_two = models.ImageField(upload_to='category_images/catview_images/%Y', blank=True, null=True)
    image_three = models.ImageField(upload_to='category_images/catview_images/%Y', blank=True, null=True)
    image_four = models.ImageField(upload_to='category_images/catview_images/%Y', blank=True, null=True)
    image_five = models.ImageField(upload_to='category_images/catview_images/%Y', blank=True, null=True)
    image_six = models.ImageField(upload_to='category_images/catview_images/%Y', blank=True, null=True)
    characteristics = models.TextField()
    habitat = models.TextField()
    diet = models.TextField()
    reproduction = models.TextField()
    notable_species = models.TextField()

    def __str__(self):
        return self.categories_type

django_project/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.db import models
from .models import Post, FunFact, Category, Category_informations

def front(request):
    return render(request, 'blog/front.html')



def home(request):
    template_name = 'blog/home.html'
    include_other = True
    context = {
        'template_name' : template_name,
        'posts' : Post.objects.all().order_by('animal'),
        'include_other' : include_other
    }   
    return render(request, template_name, context)

def sort_animals(request, animal_type=None):
    if animal_type:
        sort_query = Post.objects.filter(an_type = animal_type)
    else:
        sort_query = Post.objects.all()
        sci_name = sort_query.values_list('sci_name', flat=True)
        fav_food = sort_query.values_list('fav_food', flat=True)
        animal_cat = sci_name = sort_query.values_list('animal_cat', flat=True)
    context1 = {
        'posts' : sort_query,
        'selected_animal_type' : animal_type,
    }
    return render(request, 'blog/sorting.html', context1)

def sort_animals_type(request, animal_type=None):
    include_other = False
    if animal_type:
        sort_query = Post.objects.filter(an_type = animal_type)
    else:
        sort_query = Post.objects.all()
    context = {
        'posts' : sort_query,
        'selected_animal_type' : animal_type,
        'inlude_other' : include_other
    }   
    return render(request, 'blog/sorting_clicked.html', context)

def classification(request):
    categories = Category.objects.all()
    return render(request, 'blog/classification.html', {'categories': categories})

def class_view(request, categories_type):
    category_info = get_object_or_404(Category_informations, categories_type=categories_type)
    return render(request, 'blog/classification_view.html', {'category_info': category_info})

def funfacts(request):
    random_fact = FunFact.objects.order_by('?').first()

    context = { 
        'random_fact' : random_fact
    }
    return render(request, 'blog/fun-facts.html', context)

def search(request):
    search_query = request.GET.get('search_query', '')
    if not search_query:
        return redirect('blog:blog-front')
    search_results = Post.objects.filter(
        models.Q(an_type__icontains = search_query) |
        models.Q(animal__icontains = search_query) |
        models.Q(definition__icontains = search_query) |
        models.Q(location_discovered__icontains = search_query) |
        models.Q(location__icontains = search_query) |
        models.Q(more_info__icontains = search_query    )
        )
    return render(request, 'blog/search.html', {'search_query' : search_query, 'search_results' : search_results})

def clicked_info(request, animal_name):
    
    post = get_object_or_404(Post, animal=animal_name)
    return render(request, 'blog/clicked_info.html', {'post': post}) 

django_project/blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyJqU/RiHzGfclegnx6ZtM+2r2FNEevoQUE" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel='stylesheet' href='{% static "blog/style.css" %}'>
    <title>{% block title %}Home{% endblock title %}</title>
    <link rel='icon' href='{% static 'blog/images/purpleWCDog.png' %}' type='image/'>
  </head>
  <body>
    {% include 'blog/navbar.html' %}
    <main role="main" class="container mt-2">
      <div class="row">
        <div class="col-md-8 mx-auto">
          {% block content %}{% endblock %}
        </div>
        {% if include_other %}
          {% include 'blog/other.html' %}
        {% endif %}
      </div>
    </main>
    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">&copy; DCIT 26 BSCS3B - Tinga</p>
    
        <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        </a>
    
        <ul class="nav col-md-4 justify-content-end">
          <li class="nav-item"><a href="{% url 'blog:blog-home' %}" class="nav-link px-2 text-muted">Home</a></li>
          <li class="nav-item"><a href="{% url 'blog:blog-classification' %}" class="nav-link px-2 text-muted">Classification</a></li>
          <li class="nav-item"><a href="{% url 'blog:blog-funfacts' %}" class="nav-link px-2 text-muted">Fun Facts</a></li>
          <li class="nav-item"><a href="{% url 'blog:blog-front' %}" class="nav-link px-2 text-muted">About Us</a></li>
        </ul>
      </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

django_project/blog/templates/blog/clicked_info.html
{% extends 'blog/base.html' %}
{% block title %}{{post.animal}}{% endblock title %}
{% load static %}
{% block content %}
<div>
  <article class="media content-section mt-2 ">
    <div class="media-body">
      <div class="article-metadata text-right">
        <h2 class="text-center"><a class="article-title" href="{% url 'blog:blog-info' post.animal %}">{{ post.animal }}</a></h2>
      </div>
      
      <p class="article-content text-justify lead ">{{ post.more_info|linebreaksbr}}</p>
      <ul class="list-group list-group-flush text-center">
        <li class="list-group-item"><small class="text-muted">First Appearance: {{ post.location_discovered }}</small></li>
        <li class="list-group-item"><small class="text-muted">Location: {{ post.location }}</small></li>
        <li class="list-group-item"><small class="text-muted">Category: {{ post.animal_cat }}</small></li>
        <li class="list-group-item"><small class="text-muted">Scientific Name: {{ post.sci_name }}</small></li>
        <li class="list-group-item"><small class="text-muted">Diet: {{ post.fav_food }}</small></li>
        <li class="list-group-item"><small class="text-muted">Classification: <a class="text-bg-primary" href="{% url 'blog:class_view' categories_type=post.an_type %}">{{ post.an_type }}</a></small></li>
      </ul>
    </div>
    
  </article>

  <article class="media content-section pt-3 mt-2 text-center">
    <div class="media-body">
      <div class="article-metadata img-container zoom-container">
        <!-- Clickable image to open the modal -->
        <a href="#" data-toggle="modal" data-target="#imageModal">
          <img src="{{ post.image.url }}" class="img-fluid glow" width="500" height="500" alt="Image">
        </a>
      </div>
    </div>
  </article>
</div>

<!-- Bootstrap modal for image preview -->
<div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="imageModalLabel">{{ post.animal }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center img-container-modal">
        <!-- Larger image preview in the modal -->
        <img src="{{ post.image.url }}" class="img-fluid " alt="Image Preview">
      </div>
    </div>
  </div>
</div>
<hr class="featurette-divider">
    <div class='container d-block '>
      <div class='text-center'>
        <a class="btn btn-secondary " href="{% url 'blog:blog-home' %}" role="button">Go Back</a>
      </div>
    </div>

{% endblock %}

django_project/blog/templates/blog/front.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel='stylesheet' href='{% static "blog/style.css" %}'>
    <title>{% block title %}WiCreatures{% endblock title %}</title>
    <link rel='icon' href='{% static 'blog/images/purpleWCDog.png' %}' type='image/'>
</head>
<body>
    {% include 'blog/navbar-no-search.html' %}

    <div class="container-fluid no-margin">
        <div class="mx-5 my-5">
            <img src="{% static 'blog/images/WICREATURES-Cropped.svg' %}" class="mx-auto d-block" alt="..." width='50%'>
        </div>
        <div class="row pb-3">
            <div class="col-12 col-md-8 offset-md-2 d-flex justify-content-center align-items-center">
                <div class="divider-1">
                    <form id="searchForm" class="form-inline my-2 my-lg-0 search-form" action="{% url 'blog:blog-search'%}">
                        <input id="searchInput" class="form-control text-dark input-lg mr-sm-2 search-input" type="search" style="color: darkgray; text-decoration: None;" placeholder="Animal, Types, Habitat" aria-label="Search" name='search_query' value='{{ search_query }}'>
                        <button class="btn btn-outline-light my-2 my-sm-0 search ml-auto mr-auto" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <!--MODAL FOR ERROR HANDLING IN SEARCH-->
    <div class="modal fade" id="emptySearchModal" tabindex="-1" role="dialog" aria-labelledby="emptySearchModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="emptySearchModalLabel">Empty Search</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Search is empty. Please input something to proceed.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-dark text-white py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mx-auto">
                    <h1 class="display-5 fw-bold text-center mb-4 text-white">About Us</h1>
                    <p class="fs-5 text-center">Welcome to WiCreatures, your go-to online encyclopedia dedicated to unraveling the fascinating world of animals! At WiCreatures, we are passionate about bringing you comprehensive and reliable information about the diverse array of creatures that inhabit our planet.</p>
                    <p class="fs-5 text-center">Whether you're a nature enthusiast, a student conducting research, or simply curious about the animal kingdom, our platform is designed to be your trusted source for all things related to wildlife.</p>
                    <p class="fs-5 text-center">Our team of dedicated researchers and writers work tirelessly to provide accurate and engaging content, covering everything from the majestic to the mysterious.</p>
                    <p class="fs-5 text-center">Explore the wonders of the natural world with WiCreatures, where knowledge meets curiosity, and the beauty of wildlife unfolds before your eyes.</p>
                    <p class="fs-5 text-center">Have questions or need assistance? We're here to help! Feel free to reach out to us via email at <a class="text-decoration-none" href="https://mail.google.com/" target="_blank" rel="noopener noreferrer">wicreatures.edu.ph</a></p>
                </div>
            </div>
        </div>
    </div>
    
    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <span class="col-md-4 mb-0 text-muted">&copy; DCIT 26 BSCS3B - Tinga</span>
    
        <a href="#" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        </a>
    
        <ul class="nav col-md-4 justify-content-end">
          <li class="nav-item"><a href="{% url 'blog:blog-home' %}" class="nav-link px-2 text-muted">Home</a></li>
          <li class="nav-item"><a href="{% url 'blog:blog-classification' %}" class="nav-link px-2 text-muted">Classification</a></li>
          <li class="nav-item"><a href="{% url 'blog:blog-funfacts' %}" class="nav-link px-2 text-muted">Fun Facts</a></li>
          <li class="nav-item"><a href="{% url 'blog:blog-front' %}" class="nav-link px-2 text-muted">About Us</a></li>
        </ul>
      </footer>
    </div>
    

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function(){
            window.addEventListener('scroll', function() {
                if (window.scrollY > 50) {
                    document.getElementById('navbar_top').classList.add('fixed-top');
                    // add padding top to show content behind navbar
                    navbar_height = document.querySelector('.navbar').offsetHeight;
                    document.body.style.paddingTop = navbar_height + 'px';
                } else {
                    document.getElementById('navbar_top').classList.remove('fixed-top');
                    // remove padding top from body
                    document.body.style.paddingTop = '0';
                } 
            });
        });
        $(document).ready(function() {
            $('#searchForm').submit(function(event) {
                var searchQuery = $('#searchInput').val();
                if (!searchQuery.trim()) {
                    $('#emptySearchModal').modal('show');
                    event.preventDefault(); // Prevent form submission
                }
            });
        });
    </script>
</body>
</html>

django_project/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
<div>
  {% for post in posts %}
    <article class="media content-section mt-2 zoom-container shadow">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'blog:class_view' categories_type=post.an_type %}">{{ post.an_type }}</a>
          <small class="text-muted">{{ post.location_discovered }} |</small>
          <small class="text-muted">{{ post.location }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:blog-info' post.animal%}">{{ post.animal }}</a></h2>
        <p class="article-content">{{ post.definition }}</p>
      </div>
    </article>
  {% endfor %}
  <a href="#" class="float-right">Back to top</a>
</div>
{% endblock %}

django_project/blog/templates/blog/navbar-no-search.html
{% load static %}
<header class="site-header">
  <nav id="navbar_top" class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'blog:blog-front' %}"> <img src="{% static 'blog/images/WCDOG_MAIN.png'%}" height="30" width="50"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <div class="ml-auto d-flex text-center">
        <ul class="navbar-nav ml-auto mr-auto">
          <li class="nav-item active"><a class="nav-link" href="{% url 'blog:blog-home' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog-classification' %}">Classification</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog-funfacts' %}">Fun Facts</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

django_project/blog/templates/blog/navbar.html
{% load static %}
<header class="site-header">
  <nav id="navbar_top" class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'blog:blog-front' %}"> <img src="{% static 'blog/images/WCDOG_MAIN.png'%}" height="30" width="50"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <form class="form-inline my-2 my-lg-0" action="{% url 'blog:blog-search'%}">
        <input class="form-control mr-sm-2 ml-auto" type="search" placeholder="Search" aria-label="Search" style="color: purple;" name='search_query' value='{{ search_query }}'>
        <button class="btn btn-outline-light my-2 my-sm-0 search mr-auto ml-auto" type="submit">Search</button>
          <button class="btn btn-secondary  mr-auto mx-2" type="button" data-toggle="modal" data-target="#sortModal">
            Sort By
          </button>
      </form>
      <div class="modal fade" tabindex="-1" role="dialog" id="sortModal">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Sort By</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <a class="dropdown-item" href="{% url 'blog:blog-home' %}">All</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'blog:blog-animals' 'Amphibians' %}">Amphibians</a>  
              <a class="dropdown-item" href="{% url 'blog:blog-animals' 'Mammal' %}">Mammal</a>
              <a class="dropdown-item" href="{% url 'blog:blog-animals' 'Bird' %}">Bird</a>
              <a class="dropdown-item" href="{% url 'blog:blog-animals' 'Reptiles' %}">Reptile</a>
              <a class="dropdown-item" href="{% url 'blog:blog-animals' 'Invertebrates' %}">Invertebrates</a>
              <a class="dropdown-item" href="{% url 'blog:blog-animals' 'Fish' %}">Fish</a>
            </div>
          </div>
        </div>
      </div>

      <div class="ml-auto d-flex text-center">
        <ul class="navbar-nav ml-auto mr-auto ">
          <li class="nav-item active"><a class="nav-link" href="{% url 'blog:blog-home' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog-classification' %}">Classification</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog-funfacts' %}">Fun Facts</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<!-- Bootstrap JS and Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-YGVExjZyJ8Fb3Zrv3E1+/QDIiU6IofyNUXJefxqmsht0BpRxx/iDtkQTKxU5Kox" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyJqU/RiHzGfclegnx6ZtM+2r2FNEevoQUE" crossorigin="anonymous"></script>

<!-- Your JavaScript code -->
<script type="text/javascript">
  $(document).ready(function() {
    // Add scroll event listener
    $(window).scroll(function() {
      if ($(window).scrollTop() > 50) {
        $('#navbar_top').addClass('fixed-top');
        $('body').css('padding-top', $('.navbar').outerHeight() + 'px');
      } else {
        $('#navbar_top').removeClass('fixed-top');
        $('body').css('padding-top', '0');
      }
    });

    // Add click event listener for modal show/hide animation
    $('#sortModal').on('show.bs.modal', function() {
      $(this).find('.modal-dialog').addClass('animated fadeIn');
    });

    $('#sortModal').on('hide.bs.modal', function() {
      $(this).find('.modal-dialog').addClass('animated fadeOut');
    });
  });
  $(document).ready(function() {
            $('#searchForm').submit(function(event) {
                var searchQuery = $('#searchInput').val();
                if (!searchQuery.trim()) {
                    $('#emptySearchModal').modal('show');
                    event.preventDefault(); // Prevent form submission
                }
            });
        });
</script>

django_project/blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% block content %}
<div>
{% if search_query %}
    <h2 style='text-align: center;'>Searched for "{{ search_query }}"</h2>
{% endif %}
</div>
<div>
  {% if search_results %}
    {% for post in search_results %}
    <article class="media content-section mt-2 zoom-container">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:blog-animals2' post.an_type %}">{{ post.an_type }}</a>
              <small class="text-muted">{{ post.location_discovered }}</small>
              <small class="text-muted">{{ post.location }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:blog-info' post.animal %}">{{ post.animal }}</a></h2>
            <p class="article-content">{{ post.definition }}</p>
          </div>
        </article>
    {% endfor %}
  {% else %}
  <div style="text-align: center; text-decoration: underline;">
    <h1 class="">No results found</h1>
  </div>
  
  {% endif %}
</div>
{% endblock %}

django_project/blog/templates/blog/sorting.html
{% extends 'blog/base.html' %}
{% block title %}Sorted By: {{selected_animal_type}}{% endblock title %}
{% block content %}
<div>
{% if selected_animal_type %}
    <h2 style='text-align: center;'>Sorted By "{{ selected_animal_type }}"</h2>
{% endif %}
</div>
<div>
  {% for post in posts %}
    <article class="media content-section mt-2 zoom-container">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:blog-animals2' post.an_type %}">{{ post.an_type }}</a>
              <small class="text-muted">{{ post.location_discovered }} |</small>
              <small class="text-muted">{{ post.location }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:blog-info' post.animal %}">{{ post.animal }}</a></h2>
            <p class="article-content">{{ post.definition }}</p>
          </div>
        </article>
  {% endfor %}
</div>


<!-- animals.html -->
<!-- Add more categories as needed -->

{% endblock %}